name: money_tracking_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies: #แพ็กเกจตรงนี้ใช้ในการเขียนโค้ด
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.8.0
  dio: ^5.8.0+1
  image_picker: ^1.1.2
  intl: ^0.18.0
  animated_notch_bottom_bar: ^1.0.3

dev_dependencies: #แพ็กเกจตรงนี้แค่มาช่วยในการ Dev.
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
flutter:
  uses-material-design: true
  assets:
    - assets/images/